import { Product } from "../types/product";

export const products: Product[] = [
  {
    id: "1",
    name: "Blusa",
    price: 10000,
    sizes: ["M"],
    category: "blusas",
    image: "/images/blusas/blusa-2-talla-m.jpeg",
  },
  {
    id: "2",
    name: "Blusa",
    price: 10000,
    sizes: ["S"],
    category: "blusas",
    image: "/images/blusas/blusa-2-talla-s.jpeg",
  },
  {
    id: "3",
    name: "Blusa",
    price: 15000,
    sizes: ["M"],
    category: "blusas",
    image: "/images/blusas/blusa-3-talla-m.jpeg",
  },
  {
    id: "4",
    name: "Blusa",
    price: 10000,
    sizes: ["S"],
    category: "blusas",
    image: "/images/blusas/blusa-3-talla-s.jpeg",
  },
  {
    id: "5",
    name: "Blusa",
    price: 15000,
    sizes: ["S"],
    category: "blusas",
    image: "/images/blusas/blusa-4-talla-s.jpeg",
  },
  {
    id: "6",
    name: "Blusa",
    price: 10000,
    sizes: ["M"],
    category: "blusas",
    image: "/images/blusas/blusa-blanca-2-talla-m.jpeg",
  },
  {
    id: "7",
    name: "Blusa",
    price: 15000,
    sizes: ["M"],
    category: "blusas",
    image: "/images/blusas/blusa-blanca-talla-m.jpeg",
  },
  {
    id: "8",
    name: "Blusa",
    price: 15000,
    sizes: ["M"],
    category: "blusas",
    image: "/images/blusas/blusa-ela-2-talla-m.jpeg",
  },
  {
    id: "9",
    name: "Blusa",
    price: 10000,
    sizes: ["M"],
    category: "blusas",
    image: "/images/blusas/blusa-ela-talla-m.jpeg",
  },
  {
    id: "10",
    name: "Blusa niña",
    price: 10000,
    sizes: ["10"],
    category: "blusa",
    image: "/images/blusas/blusa-kid-talla-10.jpeg",
  },
  {
    id: "11",
    name: "Blusa",
    price: 10000,
    sizes: ["M"],
    category: "blusas",
    image: "/images/blusas/blusa-talla-m.jpeg",
  },
  {
    id: "12",
    name: "Blusa",
    price: 10000,
    sizes: ["S"],
    category: "blusas",
    image: "/images/blusas/blusa-talla-s.jpeg",
  },
  {
    id: "13",
    name: "Blusa",
    price: 15000,
    sizes: ["S", "M"],
    category: "blusas",
    image: "/images/blusas/blusa-talla-s-m.jpeg",
  },
  {
    id: "14",
    name: "Enterizo",
    price: 20000,
    sizes: ["L"],
    category: "enterizos",
    image: "/images/enterizo/enterizo-talla-l.jpeg",
  },
  {
    id: "15",
    name: "Enterizo",
    price: 20000,
    sizes: ["M"],
    category: "enterizos",
    image: "/images/enterizo/enterizo-talla-m.jpeg",
  },
  {
    id: "16",
    name: "Falda lino",
    price: 15000,
    sizes: ["12"],
    category: "faldas",
    image: "/images/faldas/falda-lino-talla-12.jpeg",
  },
  {
    id: "17",
    name: "Falda zara",
    price: 20000,
    sizes: ["8"],
    category: "faldas",
    image: "/images/faldas/falda-zara-talla-8.jpeg",
  },
  {
    id: "18",
    name: "Bobito",
    price: 10000,
    sizes: ["12"],
    category: "otros",
    image: "/images/otros/bobito-talla-12.jpeg",
  },
  {
    id: "19",
    name: "Pantalon",
    price: 15000,
    sizes: ["12"],
    category: "pantalones",
    image: "/images/pantalones/pantalon-2-talla-12.jpeg",
  },
  {
    id: "20",
    name: "Pantalon",
    price: 20000,
    sizes: ["6"],
    category: "pantalones",
    image: "/images/pantalones/pantalon-talla-6.jpeg",
  },
  {
    id: "21",
    name: "Pantalon",
    price: 15000,
    sizes: ["12"],
    category: "pantalones",
    image: "/images/pantalones/pantalon-talla-12.jpeg",
  },
  {
    id: "22",
    name: "Pantalon Tennis",
    price: 20000,
    sizes: ["8"],
    category: "pantalones",
    image: "/images/pantalones/pantalon-tennis-talla-s.jpeg",
  },
  {
    id: "23",
    name: "Pantalon YOYO",
    price: 15000,
    sizes: ["8"],
    category: "pantalones",
    image: "/images/pantalones/pantalon-yoyo-talla-8.jpeg",
  },
  {
    id: "24",
    name: "Vestido Fresco",
    price: 10000,
    sizes: ["S"],
    category: "vestidos",
    image: "/images/vestidos/vestido-fresco-talla-s.jpeg",
  },
  {
    id: "25",
    name: "Vestido Nuevo",
    price: 25000,
    sizes: ["S", "M"],
    category: "vestidos",
    image: "/images/vestidos/vestido-nuevo-talla-s-m.jpeg",
  },
];
